apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: request-port
      protocol: TCP
      name: request-port
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
