routingRules:
  rulesEngineEnabled: ROUTING_RULES_ENABLED
  rulesConfigPath: ROUTING_RULES_CONFIG_PATH

requestRouter:
  port: REQUEST_PORT
  name: prestoRouter
  historySize: QUERY_HISTORY_SIZE
  ssl: TLS_ENABLED
  keystorePath: KEYSTORE_PATH
  keystorePass: KEYSTORE_PASSWORD

dataStore:
  jdbcUrl: jdbc:mysql://MYSQL_HOST:MYSQL_PORT/MYSQL_SCHEMA
  user: MYSQL_USER
  password: MYSQL_PASSWORD
  driver: com.mysql.cj.jdbc.Driver

server:
  applicationConnectors:
    - type: http
      port: APP_PORT
  adminConnectors:
    - type: http
      port: ADMIN_PORT

# This can be adjusted based on the coordinator state
monitor:
  connectionTimeout: 15

modules:
  - com.lyft.data.gateway.ha.module.HaGatewayProviderModule
  - com.lyft.data.gateway.ha.module.ClusterStateListenerModule

managedApps:
  - com.lyft.data.gateway.ha.GatewayManagedApp
  - com.lyft.data.gateway.ha.clustermonitor.ActiveClusterMonitor

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: LOG_LEVEL

  # Logger-specific levels.
  loggers:
    com.lyft: DEBUG

  appenders:
    - type: console
    - type: file
      currentLogFilename: /gateway/logs/gateway.log
      archivedLogFilenamePattern: /gateway/logs/gateway-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 100MB
